In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv(r"../data/Amravati_merged.csv")
df.head()

,Timestamp,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
0,2018-01-01 00:00:00,59.62,109.64,3.51,23.35,15.28,18.10,26.30,0.09,87.76,...,0.03,28.16,61.96,2.64,143.21,0.0,0.0,71.10,754.78,-0.05
1,2018-01-02 00:00:00,62.46,110.93,4.02,23.87,15.96,19.64,25.33,0.09,81.70,...,0.03,27.00,71.45,2.52,143.93,0.0,0.0,71.14,755.11,-0.02
2,2018-01-03 00:00:00,72.25,140.96,5.08,41.18,26.05,25.60,28.40,0.09,79.17,...,0.04,27.13,65.69,1.98,140.27,0.0,0.0,73.65,756.97,-0.00
3,2018-01-04 00:00:00,92.60,174.57,6.09,54.06,33.71,19.58,28.87,0.11,72.15,...,0.10,26.36,65.56,1.97,126.19,0.0,0.0,78.82,758.24,0.01
4,2018-01-05 00:00:00,92.92,162.89,6.72,57.21,35.90,21.17,33.49,0.08,67.29,...,0.08,25.83,67.95,1.63,180.96,0.0,0.0,76.70,757.11,-0.01

In [7]:
df.describe()

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
count,2404.000000,2411.000000,2412.000000,2412.000000,2412.000000,2412.000000,2397.000000,2368.000000,2412.000000,2386.000000,...,2386.000000,2408.000000,2402.000000,2410.000000,2410.000000,2412.000000,2485.000000,2410.000000,2410.000000,2410.000000
mean,31.226560,62.932981,2.975863,14.727165,10.200649,12.817788,13.812268,0.626000,34.651880,0.516617,...,0.191699,28.979749,73.539462,3.144716,171.054664,0.023042,1.308549,83.295713,753.930619,-0.037407
std,24.775908,40.828206,2.880521,14.001893,9.038952,4.810488,5.345773,0.264121,14.865898,2.062178,...,0.312020,3.132165,8.018713,1.410144,54.618681,0.127059,7.755308,34.749494,4.691071,0.103247
min,1.101852,3.910000,0.250000,1.660000,0.880000,0.300000,1.790000,0.000000,7.120000,0.000000,...,0.020000,15.910000,42.760000,0.261458,57.710000,0.000000,0.000000,10.990000,741.680000,-0.580000
25%,12.172500,29.730000,1.790000,7.597500,5.690000,9.237500,10.250379,0.460000,24.267500,0.062587,...,0.100000,26.657500,68.917500,2.089687,132.878750,0.000000,0.000000,66.863125,749.900000,-0.060000
50%,23.290000,53.120000,2.139792,10.958819,7.730000,13.622153,12.895139,0.570000,31.894811,0.210000,...,0.100000,28.790000,74.125000,2.850000,156.520000,0.000000,0.000000,79.900000,754.070000,0.000000
75%,42.958472,87.992778,2.918281,16.250000,10.980000,16.310885,16.110000,0.730078,42.474688,0.600000,...,0.160000,31.180000,78.657326,3.860833,215.570000,0.000000,0.000000,93.300000,757.979792,0.020000
max,141.960000,261.750000,43.760000,140.580000,105.120000,32.930000,54.620000,1.880000,137.630000,52.550000,...,9.180000,38.750000,97.875000,9.540000,300.080000,2.790000,202.500000,382.620000,764.020000,0.240000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2485 entries, 0 to 2484
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Timestamp            2485 non-null   object
 1   PM2.5 (µg/m³)        2404 non-null   float64
 2   PM10 (µg/m³)         2411 non-null   float64
 3   NO (µg/m³)           2412 non-null   float64
 4   NO2 (µg/m³)          2412 non-null   float64
 5   NOx (ppb)            2412 non-null   float64
 6   NH3 (µg/m³)          2412 non-null   float64
 7   SO2 (µg/m³)          2397 non-null   float64
 8   CO (mg/m³)           2368 non-null   float64
 9   Ozone (µg/m³)        2412 non-null   float64
 10  Benzene (µg/m³)      2386 non-null   float64
 11  Toluene (µg/m³)      2386 non-null   float64
 12  Xylene (µg/m³)       1780 non-null   float64
 13  O Xylene (µg/m³)     0 non-null      float64
 14  Eth-Benzene (µg/m³)  0 non-null      float64
 15  MP-Xylene (µg/m³)    2386 non-null   float64
 16  AT (°C)              2408 non-null   float64
 17  RH (%)               2402 non-null   float64
 18  WS (m/s)             2410 non-null   float64
 19  WD (deg)             2410 non-null   float64
 20  RF (mm)              2412 non-null   float64
 21  TOT-RF (mm)          2485 non-null   float64
 22  SR (W/mt2)           2410 non-null   float64
 23  BP (mmHg)            2410 non-null   float64
 24  VWS (m/s)            2410 non-null   float64
dtypes: float64(24), object(1)
memory usage: 485.5+ KB